### ISSUE TITLE
when searching by eventid, specifying catalog has no impact on results

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/earthquake-event-ws#254]
https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&eventid=nc72282711

returns the same information as:

https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&eventid=nc72282711&catalog=us

Adding "catalog=us" in a multi-event search returns the "us" origin information for the returned events.  Why is this behavior different when specifying an event ID?

**Comment by jmfee-usgs** [comment]
This is currently by design, you can use any id associated to the event to get the full geojson details.

If you request either event id and *geojson* format, the results are the same (all information from all contributors):
https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=nc72282711&format=geojson
https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=usb000s5tp&format=geojson

If you request the US event id and *quakeml* format, you get the phase-data quakeml from the requested event id.  This is mainly because we haven't implemented anything to merge quakeml from multiple contributors.
https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=nc72282711
https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=usb000s5tp

How would you prefer this work?

**Comment by mhearne-usgs** [comment]
I figured this out while I was away from my desk.  The behavior as is is consistent, I just have to figure out how to make it work in my context.  You can close this issue.
